#!/usr/bin/env python3
"""Parse and write TexturePacker .tpsheet files (Unity exporter, :format=40300).

File shape: '#' comment header, ':key=value' directive lines, then one row per
sprite: 'name;x;y;w;h; pivotX;pivotY; borderL;borderR;borderT;borderB'.
Sprite rows are kept verbatim on parse so a write preserves pivots, borders,
and spacing exactly.

CLI self-test:
    python3 tpsheet.py roundtrip <file.tpsheet>
Parses and re-emits the file, then diffs directive and sprite lines against
the input (comments ignored). Exits nonzero on mismatch.
"""
import sys
from dataclasses import dataclass, field


@dataclass
class Sprite:
    name: str
    x: int
    y: int
    w: int
    h: int
    pivot_x: float = 0.5
    pivot_y: float = 0.5
    borders: tuple = (0, 0, 0, 0)  # L, R, T, B
    raw_row: str = ""


@dataclass
class Sheet:
    directives: list = field(default_factory=list)  # ordered (key, value) pairs
    sprites: list = field(default_factory=list)

    @property
    def texture(self):
        return dict(self.directives).get("texture", "")

    @property
    def size(self):
        raw = dict(self.directives).get("size", "0x0")
        w, _, h = raw.partition("x")
        return int(w), int(h)


def parse(path):
    sheet = Sheet()
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.startswith(":"):
                key, _, value = stripped[1:].partition("=")
                sheet.directives.append((key, value))
                continue
            fields = [p.strip() for p in stripped.split(";")]
            if len(fields) < 5:
                raise ValueError(f"{path}: malformed sprite row: {line!r}")
            sprite = Sprite(
                name=fields[0],
                x=int(fields[1]), y=int(fields[2]),
                w=int(fields[3]), h=int(fields[4]),
                raw_row=line,
            )
            if len(fields) >= 7:
                sprite.pivot_x, sprite.pivot_y = float(fields[5]), float(fields[6])
            if len(fields) >= 11:
                sprite.borders = tuple(int(v) for v in fields[7:11])
            sheet.sprites.append(sprite)
    return sheet


def write(path, sheet, texture_name=None, include=None):
    """Write a .tpsheet. `texture_name` overrides :texture=; `include` (a set of
    sprite names) filters the rows. The SmartUpdate hash line is intentionally
    dropped: it fingerprints the original source images and would be misleading
    on a generated sheet."""
    lines = [
        "#",
        "# Sprite sheet data for Unity.",
        "#",
        "# Generated by NASUtils atlas-localizer.",
        "#",
    ]
    for key, value in sheet.directives:
        if key == "texture" and texture_name is not None:
            value = texture_name
        lines.append(f":{key}={value}")
    lines.append("")
    for sprite in sheet.sprites:
        if include is not None and sprite.name not in include:
            continue
        lines.append(sprite.raw_row)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def _significant_lines(path):
    with open(path, encoding="utf-8") as f:
        return [l.rstrip("\n") for l in f
                if l.strip() and not l.strip().startswith("#")]


def _roundtrip(path):
    import tempfile
    sheet = parse(path)
    with tempfile.NamedTemporaryFile("w", suffix=".tpsheet", delete=False) as tmp:
        out_path = tmp.name
    write(out_path, sheet)
    original, emitted = _significant_lines(path), _significant_lines(out_path)
    if original != emitted:
        for a, b in zip(original, emitted):
            if a != b:
                print(f"mismatch:\n  in:  {a}\n  out: {b}", file=sys.stderr)
        if len(original) != len(emitted):
            print(f"line count differs: {len(original)} vs {len(emitted)}", file=sys.stderr)
        return 1
    print(f"roundtrip ok: {len(sheet.sprites)} sprites, "
          f"size={sheet.size[0]}x{sheet.size[1]}, texture={sheet.texture}")
    return 0


if __name__ == "__main__":
    if len(sys.argv) == 3 and sys.argv[1] == "roundtrip":
        sys.exit(_roundtrip(sys.argv[2]))
    print(__doc__.strip(), file=sys.stderr)
    sys.exit(2)
