version: '3.8'

services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - /volume1/docker/changesdetector/datastore:/datastore
      # - ./proxies.json:/datastore/proxies.json
    environment:
      # Default listening port inside container
      - PORT=5000
      # Log level (DEBUG is default, options: TRACE, DEBUG, INFO, SUCCESS, WARNING, ERROR, CRITICAL)
      - LOGGER_LEVEL=INFO
      # Timezone for scheduling (adjust to your location)
      - TZ=Asia/Jerusalem
      # Base URL for notifications (replace with your NAS IP/domain)
      - BASE_URL=http://192.168.1.209:8300
      # Default number of parallel fetchers
      - FETCH_WORKERS=10
      # Minimum recheck time in seconds
      - MINIMUM_SECONDS_RECHECK_TIME=30
      # For privacy, disable version checking
      - DISABLE_VERSION_CHECK=true
      # Text processing locale
      - LC_ALL=en_US.UTF-8
      # Screenshot settings
      - SCREENSHOT_MAX_HEIGHT=16000
      # Hide referer header for privacy
      - HIDE_REFERER=true
    ports:
      # External port 8300 maps to internal port 5000
      - "8300:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Uncomment below for JavaScript support (Chrome browser)
  # browser-chrome:
  #   image: dgtlmoon/sockpuppetbrowser:latest
  #   hostname: browser-chrome
  #   container_name: changedetection-browser
  #   cap_add:
  #     - SYS_ADMIN
  #   restart: unless-stopped
  #   environment:
  #     - SCREEN_WIDTH=1920
  #     - SCREEN_HEIGHT=1024
  #     - SCREEN_DEPTH=16
  #     - MAX_CONCURRENT_CHROME_PROCESSES=5
  #   volumes:
  #     - /dev/shm:/dev/shm

  # To enable Chrome browser support, uncomment the browser service above
  # and add this to changedetection environment:
  # - PLAYWRIGHT_DRIVER_URL=ws://browser-chrome:3000